26_Rails/ライブレコーディングページの実装
T-Tsujii/gyakuten_clone_group29 pull request #31
Opened 2020-10-20 01:25 UTC by Ikko-T

## 概要
ライブコーディングページの動画一覧表示

## 実装内容
- クエリーメソッド(whereメソッド)による検索条件の追加
- テンプレート内のリンク設定（link_toメソッドの第2引数にパス追加）

## 参考書
- 改訂4版 基礎 Ruby on Rails
- https://pikawaka.com/rails/where

2020-10-20 03:16 UTC, T-Tsujii requested changes

2020-10-20 03:16 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: params[:genre]).page(params[:page]).per(PER)
Rails動画教材ページで `Basic, Git, Ruby, Ruby on Rails`の動画が表示されるように条件分岐しましょう。

2020-10-22 01:28 UTC, Ikko-T commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: params[:genre]).page(params[:page]).per(PER)
修正しました。

2020-10-22 01:30 UTC, T-Tsujii approved these changes
LGTMです！

2020-10-22 01:35 UTC, Ikko-T commented
## 修正箇所
- 条件分岐による動画コンテンツの表示分け
- 1ページに表示するコンテンツ数を12へ変更
- ページネーションを表示させルため、controllerに`page(params[:page])`を追加

## 参考資料
- https://qiita.com/mugayoshi/items/80f75e93da015d82cd43
- https://qiita.com/rio_threehouse/items/313824b90a31268b0074

2020-10-22 01:36 UTC, merged