line@のコンテンツ導入
T-Tsujii/gyakuten_clone_group29 pull request #36
Opened 2020-11-02 17:49 UTC by Chibariyooh

・line_texts_controller.rbの編集
・_navbar.html.erbの編集(lineのコンテンツのみ緑色表示)関係部分に関してはapplication.scssも編集
・line_textsフォルダ内のindex.html.erb/show.html.erbの作成
・routes.rbの確認

備考)
当初、_navbar.html.erbに関して冒頭の<nav>内にbootstrapと用いるclassでのbackground-color表示がありました。
この部分はcontroller_nameでline_textsを指定してbackground-colorを指定しようと思ったのですが、bootstrapのimportantが優先されてしまっていました。
そのため、application.scssに必要な記述を行い、そちらで基の青色の指定を行いました。
```
.navbar{
  background-color: #007bff;
}
```

2020-11-02 22:08 UTC, T-Tsujii requested changes

2020-11-02 22:08 UTC, T-Tsujii commented on app/views/line_texts/index.html.erb
> +        <h2 class="mb-4" style="color:#28a745">LINE@</h2>
`Line@` の色は `Bootstrap` に用意されている色を使用していますので，こちらにしておきましょうか。

```suggestion
        <h2 class="mb-4 bg-success">LINE@</h2>
```

2020-11-02 22:08 UTC, T-Tsujii commented on app/views/line_texts/index.html.erb
> +            <th class="w-5" style="background-color:#28a745;">内容</th>
```suggestion
            <tr class="bg-success">    
                <th class="w-1">No.</th>   
                <th class="w-2">ジャンル</th>  
                <th class="w-5">内容</th>    
```

2020-11-02 22:08 UTC, T-Tsujii commented on app/views/layouts/_navbar.html.erb
> +<nav class="navbar navbar-expand-xl fixed-top navbar-dark" style="background-color:<%= controller_name == 'line_texts' ?  '#28a745' : '#007bff' %>">
```suggestion
<nav class="navbar navbar-expand-xl fixed-top navbar-dark <%= controller_name == 'line_texts' ? 'bg-primary' : 'bg-success' %>">
```

2020-11-02 22:08 UTC, T-Tsujii commented on app/javascript/stylesheets/application.scss
> +
このスタイルは必要なのでしょうか。

2020-11-03 09:50 UTC, Chibariyooh commented on app/views/line_texts/index.html.erb
> +        <h2 class="mb-4" style="color:#28a745">LINE@</h2>
こちらbgにすると背景色が変わってしまうのでtext-successとしました。

2020-11-03 09:51 UTC, Chibariyooh commented on app/views/line_texts/index.html.erb
> +            <th class="w-5" style="background-color:#28a745;">内容</th>
ありがとうございます！
修正し、確認しました！

2020-11-03 14:05 UTC, Chibariyooh commented on app/views/layouts/_navbar.html.erb
> +<nav class="navbar navbar-expand-xl fixed-top navbar-dark" style="background-color:<%= controller_name == 'line_texts' ?  '#28a745' : '#007bff' %>">
これまでcontroller_nameをstyleにつけていましたが、classにつけてみたところapplication.scssの記述消しても正常に動作しました！
確認し修正済みです。

2020-11-03 14:07 UTC, Chibariyooh commented on app/javascript/stylesheets/application.scss
> +
<nav>のclassにcontroller_nameを用いた時、こちらの記述なくても正常に作動したので消します。これまでは<nav>のstyleにcontrller_nameを用いてしまっていたためこちらの記述が必要でした・・・・・

2020-11-03 14:23 UTC, T-Tsujii approved these changes

2020-11-03 14:24 UTC, merged