task_25_トップページの作成（Ruby/Rails教材）
T-Tsujii/gyakuten_clone_group29 pull request #37
Opened 2020-11-07 11:17 UTC by s-namura

2020-11-08 00:56 UTC, T-Tsujii requested changes

2020-11-08 00:56 UTC, T-Tsujii commented on app/views/text_books/index.html.erb
> +              <a href="#" class="btn btn-primary">視聴済みにする</a>
細かいですが，

```suggestion
              <a href="#" class="btn btn-primary">読破済みにする</a>
```

2020-11-08 00:56 UTC, T-Tsujii commented on app/views/text_books/index.html.erb
> +              <img loading="lazy" alt=textbook.title class="img-fluid" width="560" height="187" src="https://d5izmuz0mcjzz.cloudfront.net/uploads/text/image/185/6d99bee3-fe84-4e6b-922f-89bea1e8734d.j
画像については，画像投稿機能を実装する必要がありますので別タスクとすべきでしょう。
一旦このままでよいと思います。

2020-11-08 00:56 UTC, T-Tsujii commented on app/controllers/text_books_controller.rb
> +  #binding.pry
このコメントアウトは削除しましょう。

```suggestion
```

2020-11-08 00:56 UTC, T-Tsujii commented on app/controllers/text_books_controller.rb
> +    #@text_books = TextBooks.all
このコメントアウトも削除しましょう。

```suggestion
```

2020-11-08 04:15 UTC, s-namura commented on app/views/text_books/index.html.erb
> +              <a href="#" class="btn btn-primary">視聴済みにする</a>
訂正致しました。

2020-11-08 04:16 UTC, s-namura commented on app/controllers/text_books_controller.rb
> +  #binding.pry
削除いたしました。

2020-11-08 04:16 UTC, s-namura commented on app/controllers/text_books_controller.rb
> +    #@text_books = TextBooks.all
削除致しました。

2020-11-11 12:05 UTC, T-Tsujii requested changes

2020-11-11 12:05 UTC, T-Tsujii commented on app/views/layouts/_navbar.html.erb
> +          <%= link_to "動画教材", movies_path(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]), class: "dropdown-item" %>
テキスト教材同様，引数は無しにしましょう。

```suggestion
          <%= link_to "動画教材", movies_path, class: "dropdown-item" %>
```

2020-11-11 12:05 UTC, T-Tsujii commented on app/views/text_books/index.html.erb
> +        </div>
カード全体をリンクにしておきましょう。

```suggestion
        <%= link_to text_book_path(textbook.id) do %>
          <div class="card border-dark mb-3">
            <div class="card-header p-0">
              <div class="card-header embed-responsive embed-responsive-16by9">
                <img loading="lazy" alt=textbook.title class="img-fluid" width="560" height="187" src="https://d5izmuz0mcjzz.cloudfront.net/uploads/text/image/185/6d99bee3-fe84-4e6b-922f-89bea1e8734d.jpeg">"
                <%= textbook.title %>
              </div>
              <div class="card-body" width="560" height="187">
                <object><a href="#" class="btn btn-primary">読破済みにする</a></object>
                <p class="card-text textbook-title">
                  <%= "No.#{i}: " + textbook.title %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
```

2020-11-12 01:26 UTC, s-namura commented on app/views/layouts/_navbar.html.erb
> +          <%= link_to "動画教材", movies_path(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]), class: "dropdown-item" %>
pathの訂正致しました。

2020-11-12 01:27 UTC, s-namura commented on app/views/text_books/index.html.erb
> +        </div>
リンクの訂正を致しました。

2020-11-12 07:31 UTC, T-Tsujii approved these changes

2020-11-12 07:31 UTC, T-Tsujii commented on app/views/text_books/index.html.erb
> +              <a target="_blank" href=textbook.id></a>
これが原因ではありませんか？小細工なしではaタグの中でaタグは使用できません。

```suggestion
```

2020-11-12 10:56 UTC, T-Tsujii approved these changes

2020-11-12 10:56 UTC, merged