task_42_検索Boxの実装
T-Tsujii/gyakuten_clone_group29 pull request #53
Opened 2020-11-23 12:55 UTC by s-namura

2020-12-02 06:13 UTC, T-Tsujii requested changes

2020-12-02 06:13 UTC, T-Tsujii commented on app/javascript/packs/application.js
> +
この2行は削除していただけますか。

```suggestion
```

2020-12-02 06:18 UTC, T-Tsujii requested changes

2020-12-02 06:18 UTC, T-Tsujii commented on app/views/text_books/_search_box.html.erb
> +  <%= f.label :title_cont, "キーワード" %>
可能であれば，Bootstrapを使うなどしてスタイルを付けてみて下さい。
https://getbootstrap.jp/docs/4.5/components/forms/

2020-12-02 06:18 UTC, T-Tsujii commented
コンフリクトの解消もお願いします。

2020-12-03 05:00 UTC, s-namura commented on app/javascript/packs/application.js
> +
削除いたしました。

2020-12-03 05:00 UTC, s-namura commented on app/views/text_books/_search_box.html.erb
> +  <%= f.label :title_cont, "キーワード" %>
Bootstrapで見た目調整いたしました。

2020-12-03 05:47 UTC, T-Tsujii requested changes

2020-12-03 05:47 UTC, T-Tsujii commented on app/views/text_books/_search_box.html.erb
> +  </div>
参考までにですが，全体を左右中央寄せにするだけの理由で`flex-box`を使うのはお勧めしません。
`max-width` と左右の `margin` を設定するのが一般的です。

フォームとボタンは `flex-box` でよいのですが，こんな感じにすると最低限の見た目になります。

```suggestion
<div class="mx-auto" style="max-width: 300px;">
  <%= search_form_for @q do |f| %>
    <div class="d-flex">
      <div class="form-group flex-grow-1">
        <%= f.search_field :title_cont, placeholder: "教材を探す", class: "form-control" %>
      </div>
      <div>
        <%= f.submit "検索", class: "btn btn-primary ml-1" %>
      </div>
    </div>
  <% end %>
</div>
```

2020-12-03 13:29 UTC, s-namura commented on app/views/text_books/_search_box.html.erb
> +  </div>
修正致しました。

2020-12-03 13:39 UTC, T-Tsujii approved these changes
LGTMです！

2020-12-03 13:50 UTC, merged