44_質問集ページ見た目調整
T-Tsujii/gyakuten_clone_group29 pull request #62
Opened 2020-12-06 01:03 UTC by Ikko-T

## 概要
質問投稿及び質問詳細画面の見た目調整

## 実装内容
- 「送信」ボタンの色とサイズ変更
- 「h1」と「h3」テキストの文字の大きさと位置調整
-  入力フォームの大きさ、形状、（divタグを用いて）位置調整

## 参考資料
- やんばるCODE教材: Bootstrap教材（その1 & 2）／HTML&CSS 実践編1, 2
- https://webst8.com/blog/bootstrap4-display/

## コメント
元アプリと完全に同じ見た目ではありません。
- 新規投稿質問一覧では余白が設定されていません。一応、paddingやmarginなど色々試しましたが出来ませんでした。そこまで見た目的に問題はないであろうと最終的に判断しましたが、必要実装でしたらご指摘お願いします！
- 質問詳細画面の各項目に表示される棒線も上記同様理由。

2020-12-06 02:19 UTC, T-Tsujii requested changes

2020-12-06 02:19 UTC, T-Tsujii commented on app/views/questions/index.html.erb
> +  <div class="question-title">
Bootstrapを使用したフォームの書き方を確認していただけますか。
https://getbootstrap.jp/docs/4.5/components/forms/

`row`を指定するのは問題ありませんが，`cols` や `size` は指定すべきものではありません。

2020-12-06 02:19 UTC, T-Tsujii commented on app/views/questions/index.html.erb
> +      <div class="row question border rounded">
スタイル部分が難しいと思いますが，元アプリではこのようなスタイルがついています。

```suggestion
      <div class="row question">
```

```scss
.question-container {
  padding: 30px 0;

  a {
    text-decoration: none;
    display: block;
    color: #333333;
    border: solid 2px #505050;
    border-radius: 10px;
    transition: .4s;

    .title-container {
      word-wrap: normal;
    }

    .title {
      font-size: 22px;
      line-height: 2;
    }

    .info {
      padding: 10px 10px 10px 20px;
      color: #BBBBBB;
    }

    :hover {
      border: solid 2px #7d9ccb;
      -webkit-transform: translateY(-5px);
      -ms-transform: translateY(-5px);
      transform: translateY(-5px);
      transition: .4s;
    }
  }

  .question {
    padding: 10px;
  }
}
```

2020-12-06 08:32 UTC, Ikko-T commented on app/views/questions/index.html.erb
> +  <div class="question-title">
`row`も削除し、`form-control`クラス名を用いました。

2020-12-06 08:34 UTC, Ikko-T commented on app/views/questions/index.html.erb
> +      <div class="row question border rounded">
上記コピペで適用しました。

2020-12-06 10:18 UTC, T-Tsujii requested changes

2020-12-06 10:18 UTC, T-Tsujii commented on app/javascript/stylesheets/application.scss
> +}
このような影響範囲の広いスタイルの付け方は避けて下さい。
他のページにも影響がでる可能性が高くなります。

```suggestion
```

2020-12-06 10:18 UTC, T-Tsujii commented on app/javascript/stylesheets/application.scss
>  td a:hover {
```
td a:hover {
  cursor: pointer;
  color: #34569e !important;
}
h1 {
  margin: 10px auto;
  max-width: 300px;
}
```

気づかなかったのですが，このあたりのスタイルも影響範囲が大きすぎるのでよろしくないですね。
別のプルリクでも良いですが，早めに削った方がよいです。

2020-12-06 10:18 UTC, T-Tsujii commented on app/javascript/stylesheets/application.scss
> +}
このスタイルは `form-group` を適切に入れていれば必要ないかもしれません。少なくとも `question-container` の中に入れるべきです。

2020-12-06 10:18 UTC, T-Tsujii commented on app/javascript/stylesheets/application.scss
> +}
これも影響範囲が大きすぎるので避けるべきです。

```suggestion
```

2020-12-06 10:18 UTC, T-Tsujii commented on app/views/questions/index.html.erb
>    </div>
`form-control` だけでなく `form-group` も必要です。また，ボタンには `btn` クラスも必要です。
https://getbootstrap.jp/docs/4.5/components/forms/

```erb
<%= form_with model: @question, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title, "【質問】" %>
    <%= form.text_area :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :detail, "【詳細】" %>
    <%= form.text_area :title, class: 'form-control' %>
  </div>
  <%= form.submit "送信", class: 'btn btn-block btn-info' %>
<% end %>
```

2020-12-06 10:18 UTC, T-Tsujii commented on app/javascript/stylesheets/application.scss
> +    :hover {
すみません，`&`の付け忘れです。
```suggestion
        &:hover {
```

2020-12-07 00:42 UTC, Ikko-T commented on app/javascript/stylesheets/application.scss
>  td a:hover {
上記は、すでに記述されていました。リモートブランチにpusした際にコンフリクトが起きたので、両方取り入れました。
ただ、上記の`h1`は削除しました。

2020-12-07 00:43 UTC, Ikko-T commented on app/javascript/stylesheets/application.scss
> +}
上記の`td a:hover`は重複していましたので、一つ削除しました。
`h1`と `h3`タグは残し、cssファイルの上部に移動しました。

2020-12-07 00:58 UTC, Ikko-T commented on app/javascript/stylesheets/application.scss
> +}
`form-group`にまとめ、`question-container`の中に入れました。

2020-12-07 00:59 UTC, Ikko-T commented on app/javascript/stylesheets/application.scss
> +    :hover {
ありがとうございます。

2020-12-07 01:03 UTC, Ikko-T commented on app/views/questions/index.html.erb
>    </div>
`question-title`と`question-detail`両方のclass名を削除し、`form-group`の中に入れました。

2020-12-07 01:06 UTC, Ikko-T commented on app/javascript/stylesheets/application.scss
> +}
`.form-control`は`question-container`の中に移動しました。

2020-12-07 01:21 UTC, Ikko-T commented on app/javascript/stylesheets/application.scss
> +}
`.form-control`はcssから削除しました。

2020-12-07 01:22 UTC, Ikko-T commented on app/views/questions/index.html.erb
>    </div>
`btn`クラスも追加しました。

2020-12-07 02:49 UTC, T-Tsujii approved these changes
LGTMです！

2020-12-07 02:49 UTC, merged