PHPテキスツページの実装
T-Tsujii/gyakuten_clone_group29 pull request #64
Opened 2020-12-11 02:01 UTC by Chibariyooh

PHPテキストページの実装を行いました。
検索の絞り込みについて疑問が残りますが、一度プルリクさせていただきます

以下、Slackでお送りした文章です。

私が問題に思っているのは検索後の表示についてです。
PHPテキストのリンクから飛ぶとPHPに関する教材が2点表示されます。
そこで例えば`基本`と検索すると、PHPという属性を持たない`基本`(Gitの基本、Ruby on Rails の基本)が現状表示されます。
そこで
f params[:genre].nil?
      @q = TextBook.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails","Php"]).ransack(params[:q])
      @text_books = @q.result
    else
      @q = TextBook.where(genre: params[:genre]).ransack(params[:q])
      @text_books = TextBook.where(genre: params[:genre])
    end
とgenreの中に“Php”を追加するとphpの属性を持つ基本(PHPの基本)も上の二つに加えて検索結果に表示されるようになります。
これで確かにPHP属性の検索ができるようになったのですが、PHP属性ではない要素も選択されてしまいます。
逆も然りでRuby/Railsテキストで検索に`基本`と記入するとPHP属性の要素も選択されます。
これは仕様上仕方ないことなのでしょうか？
navbarでgenreの指定などやってみたのですが、方法が思い付かず、アドバイスいただきたいです。

2020-12-11 02:37 UTC, T-Tsujii requested changes

2020-12-11 02:37 UTC, T-Tsujii commented on app/controllers/text_books_controller.rb
>    end
`nil` だった場合（Railsテキスト教材の場合）にPhpを入れてしまっているのが原因ではありませんか？

```rb
def index
  if params[:genre].nil?
    @q = TextBook.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]).ransack(params[:q])
  else
    @q = TextBook.where(genre: params[:genre]).ransack(params[:q])
  end
  @text_books = @q.result
end
```

2020-12-11 02:37 UTC, T-Tsujii commented on app/views/layouts/_navbar.html.erb
> +          <%= link_to "Ruby/Rails教材", text_books_path(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]), class: "dropdown-item" %>
この書き方で配列を渡してはいけません。

```suggestion
          <%= link_to "Ruby/Rails教材", text_books_path, class: "dropdown-item" %>
```

2020-12-11 02:37 UTC, T-Tsujii commented on css/actiontext.css
> +.trix-content .attachment-gallery > action-text-attachment,
不要なファイルが大量に作成されています。

https://github.com/T-Tsujii/gyakuten_clone_group29/pull/64/files#
を確認し，コントローラ，scss，ビューの3ファイル以外は全て削除しておいて下さい。

2020-12-18 09:04 UTC, T-Tsujii requested changes

2020-12-18 09:04 UTC, T-Tsujii commented on app/controllers/text_books_controller.rb
>        @text_books = @q.result.order(:id)
```suggestion
```

2020-12-18 09:04 UTC, T-Tsujii commented on app/controllers/text_books_controller.rb
> +    @text_books = @q.result
6行目についているorderをこちらに反映させて下さい。

```suggestion
    @text_books = @q.result.order(:id)
```

2020-12-18 09:04 UTC, T-Tsujii commented on app/views/text_books/_search_box.html.erb
> +    <%= f.hidden_field :genre, value: params[:genre] %>
どうも私の誤解だったようで，元の表記だとparams[:genre] ではなく，params[:q][:genre] が飛んでいたようです。

```
<ActionController::Parameters {"q"=>{"genre"=>"Php", "title_cont"=>"基本"}, "commit"=>"検索", "controller"=>"text_books", "action"=>"index"} permitted: false>
```

`hidden_field_tag` を使用すれば，qの中にパラメータが入ってしまうのを防げますので，こちらに変更されるとよいでしょう。

```suggestion
    <%= hidden_field_tag :genre, params[:genre] %>
```

2020-12-21 01:04 UTC, Chibariyooh commented on app/views/text_books/_search_box.html.erb
> +    <%= f.hidden_field :genre, value: params[:genre] %>
この書き方をすると今度はRailsの教材ページでqの中にパラメータが渡されず、該当する教材がなくなってしまいます。。

```
Started GET "/text_books?genre=&q%5Btitle_cont%5D=%E5%9F%BA%E6%9C%AC&commit=%E6%A4%9C%E7%B4%A2" for ::1 at 2020-12-21 09:59:27 +0900
Processing by TextBooksController#index as HTML
  Parameters: {"genre"=>"", "q"=>{"title_cont"=>"基本"}, "commit"=>"検索"}
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Rendering text_books/index.html.erb within layouts/application
  Rendered text_books/_search_box.html.erb (Duration: 3.0ms | Allocations: 522)
  TextBook Load (0.3ms)  SELECT "text_books".* FROM "text_books" WHERE "text_books"."genre" = $1 AND "text_books"."title" ILIKE '%基本%'  [["genre", ""]]
  ↳ app/views/text_books/index.html.erb:8
  Rendered text_books/index.html.erb within layouts/application (Duration: 12.7ms | Allocations: 1748)
[Webpacker] Everything's up-to-date. Nothing to do
  Rendered layouts/_navbar.html.erb (Duration: 7.6ms | Allocations: 1322)
  Rendered layouts/_flash.html.erb (Duration: 1.5ms | Allocations: 153)
Completed 200 OK in 81ms (Views: 66.1ms | ActiveRecord: 0.8ms | Allocations: 9755)
```

つまり、navbarなどで"Php"とgenreを指定したようにRails も指定する記述が必要だと思うのですが、いかがでしょうか？

2020-12-21 01:14 UTC, T-Tsujii requested changes

2020-12-21 01:14 UTC, T-Tsujii commented on app/controllers/text_books_controller.rb
>        @q = TextBook.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]).ransack(params[:q])
`@q` の定義が重複しています。共通していますので，if文の後に記載するだけにしましょう。
そして，https://github.com/T-Tsujii/gyakuten_clone_group29/pull/64/files#r546464117 の件に対応するため `blank?` に変更しましょう。

```rb
  def index
    if params[:genre].blank?
      @q = TextBook.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]).ransack(params[:q])
    else
      @q = TextBook.where(genre: params[:genre]).ransack(params[:q])
    end
      @text_books = @q.result.order(:id)
  end
```

2020-12-21 01:14 UTC, T-Tsujii commented on app/views/text_books/_search_box.html.erb
> +    <%= f.hidden_field :genre, value: params[:genre] %>
これはコントローラで `nil?` ではなく `blank?` を使えば解決するはずです。

2020-12-21 01:27 UTC, T-Tsujii commented on app/views/text_books/_search_box.html.erb
> +    <%= f.hidden_field :genre, value: params[:genre] %>
もしくは，`params[:genre]` が存在する時だけ埋め込むように記述してもよいですね。

```

    <%= hidden_field_tag :genre, params[:genre] if params[:genre] %>

```

2020-12-24 22:24 UTC, T-Tsujii approved these changes
LGTMです！

2020-12-25 01:02 UTC, merged